// Regenerates docs/dev/graduations.md and graduations-cn.md from the
// code (English is canonical; the -cn file is its translation).
//
// This is the per-scale audit sheet: it lists, for every scale of both models,
// the measured interval source, the steps and levels of each segment, the
// printed numbers, and the row/display flags (adjacency, tickEdge, tick
// direction, numbers above/below). The "drawn ticks" line is the real output of
// getScaleTicks, so the document can never drift from the code.
//
// It runs as part of `npm test` and rewrites the files deterministically.
import { it } from 'vitest'
import { writeFileSync } from 'node:fs'
import { MODEL_1002 } from '../data/model1002'
import { MODEL_57 } from '../data/model57'
import { getScaleTicks } from './scaleFunctions'
import { defaultLabelFormat } from './scaleCalculation'
import type {
  GraduationInterval,
  Mapping,
  ScaleDefinition,
  ScaleSectionGroup,
} from '../types/scale'

function stepsText(iv: GraduationInterval): string {
  return iv.steps.map((s) => `${s.step}@L${s.level}`).join(' ')
}

// A one-line summary of a ScaleCalculation's mapping. A generated dev doc, so
// the tokens stay untranslated.
function mapSummary(m: Mapping): string {
  switch (m.kind) {
    case 'log':
      return `map=log anchor=${m.anchor}${m.normalize ? ' normalize' : ''}`
    case 'linear':
      return 'map=linear'
    case 'fn':
      return `map=fn ${m.fn} from=${m.from}`
    case 'valueFn':
      return `map=valueFn ${m.fn} from=${m.from}`
    case 'expr':
      return `map=expr ${m.position}`
    case 'custom':
      return 'map=custom'
  }
}

// How the renderer draws the graduations: only a `floor` shared-edge row rises
// from the bottom edge; everything else hangs downwards.
function tickDirection(s: ScaleDefinition): 'up' | 'down' {
  return s.tickEdge === 'floor' ? 'up' : 'down'
}

function adjacencyOf(s: ScaleDefinition, i: number, count: number): string {
  const first = i === 0
  const last = i === count - 1
  if (first && (s.section === 'middle' || s.section === 'lower')) return 'top'
  if (last && (s.section === 'upper' || s.section === 'middle')) return 'bottom'
  return '-'
}

const EN = {
  h1: '# Graduation / drawing model per scale',
  note: [
    '> Generated by `packages/core/src/engine/graduationReport.test.ts` - do not edit by hand;',
    '> it is rewritten on every `npm test`. For every scale of both models it lists',
    '> the measured interval source, the steps and levels of each segment, the',
    '> printed numbers, and the row flags (adjacency, tickEdge, tick direction,',
    '> numbers above/below). The "drawn ticks" line is the real output of',
    '> `getScaleTicks`; "position" is in C/D decade units, where 0..1 is the C/D',
    '> span (values outside it overflow the graduations area).',
  ],
  titles: { front1002: '1002 front', back1002: '1002 back', front57: 'Type 57 front' },
  label: {
    adjacency: 'adjacency',
    tickEdge: 'tickEdge',
    ticks: 'ticks',
    numbers: 'numbers',
    above: 'above',
    below: 'below',
    up: 'up',
    down: 'down',
    slide: 'slide',
    body: 'body',
    shared: 'shared labels',
    notes: 'notes',
    drawn: 'drawn ticks',
    printed: 'printed',
    source: 'source',
    sourceTable: 'source',
    marks: 'marks',
    span: 'C/D span is 0..1',
  },
}

const CN = {
  h1: '# 各标尺的刻度 / 绘制模型',
  note: [
    '> 由 `packages/core/src/engine/graduationReport.test.ts` 生成——请勿手改；每次 `npm test` 都会重写。',
    '> 它逐条列出两款尺每条标尺：实测区间来源、每段的步长与档级、印数，以及行属性',
    '> （adjacency 贴边、tickEdge 共用边、刻度朝向、数字在上/下）。"实际刻度"一行是',
    '> `getScaleTicks` 的真实输出；"位置"以 C/D 十进制为单位，0..1 为 C/D 范围',
    '>（超出即溢出到刻度区之外）。',
  ],
  titles: { front1002: '1002 正面', back1002: '1002 背面', front57: '57 型 正面' },
  label: {
    adjacency: '贴边',
    tickEdge: '共用边',
    ticks: '刻度朝向',
    numbers: '数字',
    above: '在上',
    below: '在下',
    up: '向上',
    down: '向下',
    slide: '动尺',
    body: '定尺',
    shared: '共享标注',
    notes: '备注',
    drawn: '实际刻度',
    printed: '印数',
    source: '数据来源',
    sourceTable: '数据来源',
    marks: '记号',
    span: 'C/D 范围为 0..1',
  },
}

type Lang = typeof EN

function scaleBlock(s: ScaleDefinition, i: number, count: number, L: Lang): string[] {
  const out: string[] = []
  const ticks = getScaleTicks(s)
  const lv = { 1: 0, 2: 0, 3: 0 } as Record<number, number>
  for (const t of ticks) lv[t.level]++
  const labels = ticks.filter((t) => t.label).map((t) => t.label as string)
  const positions = ticks.map((t) => t.position)
  const pMin = positions.length ? Math.min(...positions) : 0
  const pMax = positions.length ? Math.max(...positions) : 0
  out.push(`### ${s.name} (type ${s.type})`)
  out.push(
    `- ${s.side} / ${s.section} / ${s.orientation} / ${s.isMovable ? L.label.slide : L.label.body}` +
      ` / ${L.label.adjacency}=${adjacencyOf(s, i, count)}` +
      ` / ${L.label.tickEdge}=${s.tickEdge ?? '-'}` +
      ` / ${L.label.ticks}=${L.label[tickDirection(s)]}` +
      ` / ${L.label.numbers}=${s.numbersBelow ? L.label.below : L.label.above}`,
  )
  if (s.sharedLabels?.length)
    out.push(`- ${L.label.shared}: ${s.sharedLabels.map((x) => x.name).join(', ')}`)
  if (s.notes?.length)
    out.push(
      `- ${L.label.notes}: ${s.notes
        .map((n) => (typeof n === 'string' ? n : n.map((p) => p.text).join('')))
        .join(' | ')}`,
    )
  out.push(
    `- ${L.label.drawn}: ${ticks.length} (L1=${lv[1]} L2=${lv[2]} L3=${lv[3]}), ` +
      `position ${pMin.toFixed(4)} .. ${pMax.toFixed(4)} (${L.label.span})`,
  )
  out.push(`- ${L.label.printed}: ${labels.join(' ')}`)
  if (s.calc) {
    const c = s.calc
    const flags = [`domain=${c.domain[0]}..${c.domain[1]}`]
    if ((c.decades ?? 1) > 1) flags.push(`decades=${c.decades}`)
    if (c.decreasing) flags.push('decreasing')
    out.push(`- ${L.label.source}: ScaleCalculation ${mapSummary(c.map)} ${flags.join(' ')}`)
    for (const iv of c.intervals) out.push(`  - [${iv.from}, ${iv.to}) ${stepsText(iv)}`)
    if (c.labels?.length)
      out.push(
        `  - ${L.label.printed}: ${c.labels
          .map((x) =>
            typeof x === 'number' ? (c.labelFormat?.(x) ?? defaultLabelFormat(x)) : x.text,
          )
          .join(' ')}`,
      )
    if (c.marks?.length)
      out.push(`  - ${L.label.marks}: ${c.marks.map((m) => `${m.value}=${m.label}`).join(' ')}`)
  }
  out.push('')
  return out
}

function sideSection(title: string, group: ScaleSectionGroup, L: Lang): string[] {
  const out = [`## ${title}`, '']
  for (const scales of [group.upper, group.middle, group.lower]) {
    scales.forEach((s, i) => out.push(...scaleBlock(s, i, scales.length, L)))
  }
  return out
}

function report(L: Lang): string {
  const lines: string[] = [
    L.h1,
    '',
    ...L.note,
    '',
    ...sideSection(L.titles.front1002, MODEL_1002.front, L),
    ...sideSection(L.titles.back1002, MODEL_1002.back, L),
    ...sideSection(L.titles.front57, MODEL_57.front, L),
  ]
  return lines.join('\n') + '\n'
}

it('regenerates docs/dev/graduations.md and graduations-cn.md', () => {
  writeFileSync('docs/dev/graduations.md', report(EN))
  writeFileSync('docs/dev/graduations-cn.md', report(CN))
})
